[package]
name = "weser"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
clio = { version = "0.3.5", features = ["clap-parse"] }
system = { path = "../system" }
